"""word not unique

Revision ID: 146c8a611238
Revises: 2844267fc9fd
Create Date: 2026-05-03 23:18:08.920007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146c8a611238'
down_revision: Union[str, Sequence[str], None] = '2844267fc9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dictionary_word'), table_name='dictionary')
    op.create_index(op.f('ix_dictionary_word'), 'dictionary', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dictionary_word'), table_name='dictionary')
    op.create_index(op.f('ix_dictionary_word'), 'dictionary', ['word'], unique=1)
    # ### end Alembic commands ###
