"""Initial dictionary table

Revision ID: 2844267fc9fd
Revises: 
Create Date: 2026-05-03 22:57:15.019837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2844267fc9fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_id'), 'dictionary', ['id'], unique=False)
    op.create_index(op.f('ix_dictionary_word'), 'dictionary', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dictionary_word'), table_name='dictionary')
    op.drop_index(op.f('ix_dictionary_id'), table_name='dictionary')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
