"""Add part of speech

Revision ID: e07ba785f4bc
Revises: 5f6e04f0555b
Create Date: 2026-05-06 19:42:55.018210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07ba785f4bc'
down_revision: Union[str, Sequence[str], None] = '5f6e04f0555b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('part_of_speech', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'part_of_speech')
    # ### end Alembic commands ###
