"""add hsk_words and text_segments

Revision ID: fc4176fcfe3f
Revises: 
Create Date: 2026-05-15 22:27:00.586178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4176fcfe3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_id'), 'dictionary', ['id'], unique=False)
    op.create_index(op.f('ix_dictionary_word'), 'dictionary', ['word'], unique=False)
    op.create_table('hsk_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hsk_words_id'), 'hsk_words', ['id'], unique=False)
    op.create_index(op.f('ix_hsk_words_word'), 'hsk_words', ['word'], unique=True)
    op.create_table('user_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_texts_id'), 'user_texts', ['id'], unique=False)
    op.create_table('text_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('original_word', sa.String(), nullable=False),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('hsk_level', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['user_texts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_segments_id'), 'text_segments', ['id'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['user_texts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_id'), 'translations', ['id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['user_texts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_table('word_translation_association',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id', 'translation_id'),
    sa.UniqueConstraint('word_id', 'translation_id', name='uq_word_translation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_translation_association')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_translations_id'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_text_segments_id'), table_name='text_segments')
    op.drop_table('text_segments')
    op.drop_index(op.f('ix_user_texts_id'), table_name='user_texts')
    op.drop_table('user_texts')
    op.drop_index(op.f('ix_hsk_words_word'), table_name='hsk_words')
    op.drop_index(op.f('ix_hsk_words_id'), table_name='hsk_words')
    op.drop_table('hsk_words')
    op.drop_index(op.f('ix_dictionary_word'), table_name='dictionary')
    op.drop_index(op.f('ix_dictionary_id'), table_name='dictionary')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
